In [1]:
!pip install dtale

Collecting dtale
  Downloading dtale-1.32.1-py2.py3-none-any.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 3.9 MB/s eta 0:00:01
Collecting xarray; python_version >= "3.0"
  Downloading xarray-0.16.2-py3-none-any.whl (736 kB)
     |████████████████████████████████| 736 kB 4.5 MB/s eta 0:00:01
Collecting dash>=1.5.0
  Downloading dash-1.19.0.tar.gz (75 kB)
     |████████████████████████████████| 75 kB 444 kB/s eta 0:00:01
Requirement already satisfied: pandas in /home/inder/miniconda3/lib/python3.8/site-packages (from dtale) (1.2.0)
Collecting dash-daq
  Downloading dash_daq-0.5.0.tar.gz (642 kB)
     |████████████████████████████████| 642 kB 3.9 MB/s eta 0:00:01
Requirement already satisfied: plotly>=4.9.0 in /home/inder/.local/lib/python3.8/site-packages (from dtale) (4.14.1)
Collecting squarify
  Downloading squarify-0.4.3-py3-none-any.whl (4.3 kB)
Requirement already satisfied: future>=0.14.0 in /home/inder/miniconda3/lib/python3.8/site-packages (from dtale) (0.18.2)
Collecting dash-bootstrap-components; python_version > "3.0"
  Downloading dash_bootstrap_components-0.11.1-py2.py3-none-any.whl (187 kB)
     |████████████████████████████████| 187 kB 2.5 MB/s eta 0:00:01
Requirement already satisfied: Flask>=1.0 in /home/inder/.local/lib/python3.8/site-packages (from dtale) (1.1.2)
Collecting ppscore; python_version >= "3.6"
  Downloading ppscore-1.2.0.tar.gz (47 kB)
     |████████████████████████████████| 47 kB 411 kB/s eta 0:00:01
Collecting flask-ngrok; python_version > "3.0"
  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)
Requirement already satisfied: scipy in /home/inder/.local/lib/python3.8/site-packages (from dtale) (1.6.0)
Collecting Flask-Compress
  Downloading Flask_Compress-1.8.0-py3-none-any.whl (7.2 kB)
Collecting kaleido
  Downloading kaleido-0.1.0-py2.py3-none-manylinux1_x86_64.whl (74.6 MB)
     |████████████████████████████████| 74.6 MB 50 kB/s  eta 0:00:01
Collecting lz4; python_version > "3.0"
  Downloading lz4-3.1.3-cp38-cp38-manylinux2010_x86_64.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 3.4 MB/s eta 0:00:01
Collecting dash-colorscales
  Downloading dash_colorscales-0.0.4.tar.gz (62 kB)
     |████████████████████████████████| 62 kB 20 kB/s  eta 0:00:01
Requirement already satisfied: scikit-learn>='0.21.0 in /home/inder/.local/lib/python3.8/site-packages (from dtale) (0.24.0)
Requirement already satisfied: six in /home/inder/.local/lib/python3.8/site-packages (from dtale) (1.15.0)
Collecting strsimpy
  Downloading strsimpy-0.2.0-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 74 kB/s  eta 0:00:01
Requirement already satisfied: itsdangerous in /home/inder/.local/lib/python3.8/site-packages (from dtale) (1.1.0)
Collecting networkx; python_version >= "3.0"
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 4.6 MB/s eta 0:00:01
Collecting statsmodels
  Downloading statsmodels-0.12.1-cp38-cp38-manylinux1_x86_64.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 1.7 MB/s eta 0:00:01
Requirement already satisfied: requests in /home/inder/.local/lib/python3.8/site-packages (from dtale) (2.24.0)
Requirement already satisfied: setuptools>=38.4 in /home/inder/miniconda3/lib/python3.8/site-packages (from xarray; python_version >= "3.0"->dtale) (50.3.1.post20201107)
Requirement already satisfied: numpy>=1.15 in /home/inder/.local/lib/python3.8/site-packages (from xarray; python_version >= "3.0"->dtale) (1.19.5)
Collecting dash_renderer==1.9.0
  Downloading dash_renderer-1.9.0.tar.gz (1.0 MB)
     |████████████████████████████████| 1.0 MB 2.7 MB/s eta 0:00:01
Collecting dash-core-components==1.15.0
  Downloading dash_core_components-1.15.0.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 470 kB/s eta 0:00:01
Collecting dash-html-components==1.1.2
  Downloading dash_html_components-1.1.2.tar.gz (188 kB)
     |████████████████████████████████| 188 kB 4.9 MB/s eta 0:00:01
Collecting dash-table==4.11.2
  Downloading dash_table-4.11.2.tar.gz (1.8 MB)
     |████████████████████████████████| 1.8 MB 4.5 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.7.3 in /home/inder/miniconda3/lib/python3.8/site-packages (from pandas->dtale) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /home/inder/miniconda3/lib/python3.8/site-packages (from pandas->dtale) (2020.5)
Requirement already satisfied: retrying>=1.3.3 in /home/inder/.local/lib/python3.8/site-packages (from plotly>=4.9.0->dtale) (1.3.3)
Requirement already satisfied: Jinja2>=2.10.1 in /home/inder/.local/lib/python3.8/site-packages (from Flask>=1.0->dtale) (2.11.2)
Requirement already satisfied: click>=5.1 in /home/inder/miniconda3/lib/python3.8/site-packages (from Flask>=1.0->dtale) (7.1.2)
Requirement already satisfied: Werkzeug>=0.15 in /home/inder/.local/lib/python3.8/site-packages (from Flask>=1.0->dtale) (1.0.1)
Collecting brotli
  Downloading Brotli-1.0.9-cp38-cp38-manylinux1_x86_64.whl (357 kB)
     |████████████████████████████████| 357 kB 6.1 MB/s eta 0:00:01
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/inder/.local/lib/python3.8/site-packages (from scikit-learn>='0.21.0->dtale) (2.1.0)
Requirement already satisfied: joblib>=0.11 in /home/inder/.local/lib/python3.8/site-packages (from scikit-learn>='0.21.0->dtale) (1.0.0)
Requirement already satisfied: decorator>=4.3.0 in /home/inder/.local/lib/python3.8/site-packages (from networkx; python_version >= "3.0"->dtale) (4.4.2)
Collecting patsy>=0.5
  Downloading patsy-0.5.1-py2.py3-none-any.whl (231 kB)
     |████████████████████████████████| 231 kB 4.6 MB/s eta 0:00:01
Requirement already satisfied: certifi>=2017.4.17 in /home/inder/miniconda3/lib/python3.8/site-packages (from requests->dtale) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /home/inder/miniconda3/lib/python3.8/site-packages (from requests->dtale) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/inder/miniconda3/lib/python3.8/site-packages (from requests->dtale) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /home/inder/.local/lib/python3.8/site-packages (from requests->dtale) (2.9)
Requirement already satisfied: MarkupSafe>=0.23 in /home/inder/miniconda3/lib/python3.8/site-packages (from Jinja2>=2.10.1->Flask>=1.0->dtale) (1.1.1)
Building wheels for collected packages: dash, dash-daq, ppscore, dash-colorscales, dash-renderer, dash-core-components, dash-html-components, dash-table
  Building wheel for dash (setup.py) ... done
  Created wheel for dash: filename=dash-1.19.0-py3-none-any.whl size=84011 sha256=206240e5246996625ff396f22a2f351713512df6b43dad46ebf9e061bb784875
  Stored in directory: /home/inder/.cache/pip/wheels/e7/27/2f/a9f9bf858843b5365bcb311a80f0b2379737caf4ec50b2ae3a
  Building wheel for dash-daq (setup.py) ... done
  Created wheel for dash-daq: filename=dash_daq-0.5.0-py3-none-any.whl size=669701 sha256=957d4ee7c2451c3272370af630969185a32069751c98aa661f80ee22ab710b27
  Stored in directory: /home/inder/.cache/pip/wheels/00/35/e5/57e90f10c529601c6627400513cb65dd5adb09752411f5a050
  Building wheel for ppscore (setup.py) ... done
  Created wheel for ppscore: filename=ppscore-1.2.0-py2.py3-none-any.whl size=13050 sha256=b2e4501931c6ec0599626c516ac206426ac0538f4c9154953449663da1dde308
  Stored in directory: /home/inder/.cache/pip/wheels/fb/0e/65/da65ce669381fc01b6ef990d301d3586991f89bff1175877a4
  Building wheel for dash-colorscales (setup.py) ... done
  Created wheel for dash-colorscales: filename=dash_colorscales-0.0.4-py3-none-any.whl size=62598 sha256=8acae6994efd36a3b026a91b25cf78d704422917cc6ce3ea0a8964b603efb3e8
  Stored in directory: /home/inder/.cache/pip/wheels/fe/33/33/172dbfe1efc739352828854a113df599a428b58f68ed0c4f75
  Building wheel for dash-renderer (setup.py) ... done
  Created wheel for dash-renderer: filename=dash_renderer-1.9.0-py3-none-any.whl size=1014872 sha256=887f3eb62cd39a731c9d7f885b50b239308749c450fe4c5eba9d66428895f27e
  Stored in directory: /home/inder/.cache/pip/wheels/08/94/09/e11ba8ae5d97e1c8ff5be0ac1f7cf42642eec6ea94ed1e4b44

  Building wheel for dash-core-components (setup.py) ... done
  Created wheel for dash-core-components: filename=dash_core_components-1.15.0-py3-none-any.whl size=3527011 sha256=f977256e05e9cda7d535fa142fd43c8380b1470c4f5259a5f929ecd10d9dfd96
  Stored in directory: /home/inder/.cache/pip/wheels/e3/e6/0e/759ca580c568aad2436521fa6df67f53a141dc1ab8f040c4c7
  Building wheel for dash-html-components (setup.py) ... done
  Created wheel for dash-html-components: filename=dash_html_components-1.1.2-py3-none-any.whl size=427831 sha256=9b875b9b150b8a6f357186946f5be03c1fea7becb555a59b9cfcb94f96142eec
  Stored in directory: /home/inder/.cache/pip/wheels/8a/bc/a8/7ad1d354777cfe77413fd7a092e07d7cc82f88f98997f4c463
  Building wheel for dash-table (setup.py) ... done
  Created wheel for dash-table: filename=dash_table-4.11.2-py3-none-any.whl size=1839869 sha256=5fe1293e8def8a6425c9db5e7c833c1237e4566ba3c9462f9ea32caa00265dbe
  Stored in directory: /home/inder/.cache/pip/wheels/cc/1d/a0/720dcf854e410eddbe44f8434f4d3a6332fdd085178eeac4f9
Successfully built dash dash-daq ppscore dash-colorscales dash-renderer dash-core-components dash-html-components dash-table
Installing collected packages: xarray, brotli, Flask-Compress, dash-renderer, dash-core-components, dash-html-components, dash-table, dash, dash-daq, squarify, dash-bootstrap-components, ppscore, flask-ngrok, kaleido, lz4, dash-colorscales, strsimpy, networkx, patsy, statsmodels, dtale
Successfully installed Flask-Compress-1.8.0 brotli-1.0.9 dash-1.19.0 dash-bootstrap-components-0.11.1 dash-colorscales-0.0.4 dash-core-components-1.15.0 dash-daq-0.5.0 dash-html-components-1.1.2 dash-renderer-1.9.0 dash-table-4.11.2 dtale-1.32.1 flask-ngrok-0.0.25 kaleido-0.1.0 lz4-3.1.3 networkx-2.5 patsy-0.5.1 ppscore-1.2.0 squarify-0.4.3 statsmodels-0.12.1 strsimpy-0.2.0 xarray-0.16.2

In [2]:
import dtale

In [3]:
import seaborn as sns

In [5]:
print(sns.get_dataset_names())

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'exercise', 'flights', 'fmri', 'gammas', 'geyser', 'iris', 'mpg', 'penguins', 'planets', 'tips', 'titanic']

In [7]:
df=sns.load_dataset('planets')

In [8]:
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [9]:
df.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [33]:
dtale.show(df)

http://inder-G5-5587:40000/dtale/main/1
It looks like this data may have already been loaded to D-Tale based on shape and column names. Here is URL of the data that seems to match it:

None

If you still want to load this data please use the following command:

dtale.show(df, ignore_duplicate=True)
Exception occurred while processing request: window must be an integer
Traceback (most recent call last):
  File "/home/inder/miniconda3/lib/python3.8/site-packages/dtale/views.py", line 84, in _handle_exceptions
    return func(*args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/dtale/views.py", line 2472, in get_column_analysis
    ordinal_data = getattr(
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1867, in rolling
    return RollingGroupby(self, *args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 752, in __init__
    super().__init__(obj, *args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 113, in __init__
    self.validate()
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 1921, in validate
    raise ValueError("window must be an integer")
ValueError: window must be an integer
Exception occurred while processing request: window must be an integer
Traceback (most recent call last):
  File "/home/inder/miniconda3/lib/python3.8/site-packages/dtale/views.py", line 84, in _handle_exceptions
    return func(*args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/dtale/views.py", line 2472, in get_column_analysis
    ordinal_data = getattr(
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1867, in rolling
    return RollingGroupby(self, *args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 752, in __init__
    super().__init__(obj, *args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 113, in __init__
    self.validate()
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 1921, in validate
    raise ValueError("window must be an integer")
ValueError: window must be an integer

2021-01-26 16:14:36,584 - ERROR    - Exception occurred while processing request: window must be an integer
Traceback (most recent call last):
  File "/home/inder/miniconda3/lib/python3.8/site-packages/dtale/views.py", line 84, in _handle_exceptions
    return func(*args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/dtale/views.py", line 2472, in get_column_analysis
    ordinal_data = getattr(
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/groupby/groupby.py", line 1867, in rolling
    return RollingGroupby(self, *args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 752, in __init__
    super().__init__(obj, *args, **kwargs)
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 113, in __init__
    self.validate()
  File "/home/inder/miniconda3/lib/python3.8/site-packages/pandas/core/window/rolling.py", line 1921, in validate
    raise ValueError("window must be an integer")
ValueError: window must be an integer

Executing shutdown due to inactivity...
Executing shutdown due to inactivity...

2021-01-26 17:14:36,028 - INFO     - Executing shutdown due to inactivity...

Executing shutdown...
Executing shutdown...

2021-01-26 17:14:36,037 - INFO     - Executing shutdown...

In [20]:
stats

          count        mean         std   min    25%    50%    75%     max
distance  808.0  264.069282  733.116493  1.35  32.56  55.25  178.5  8500.0

In [23]:
s = df['number']
q1 = s.quantile(0.25)
q3 = s.quantile(0.75)
iqr = q3 - q1
iqr_lower = q1 - 1.5 * iqr
iqr_upper = q3 + 1.5 * iqr
outliers = dict(s[(s < iqr_lower) | (s > iqr_upper)])

In [24]:
outliers

{17: 5,
 18: 5,
 19: 5,
 20: 5,
 21: 5,
 64: 4,
 65: 4,
 66: 4,
 67: 4,
 125: 4,
 126: 4,
 127: 4,
 128: 4,
 130: 6,
 131: 6,
 132: 6,
 133: 6,
 134: 6,
 135: 6,
 142: 4,
 143: 4,
 144: 4,
 145: 4,
 230: 6,
 231: 6,
 232: 6,
 233: 6,
 234: 6,
 235: 6,
 309: 6,
 310: 6,
 311: 6,
 312: 6,
 313: 6,
 314: 6,
 514: 4,
 515: 4,
 516: 4,
 517: 4,
 643: 4,
 644: 4,
 645: 4,
 646: 4,
 664: 6,
 665: 6,
 666: 6,
 667: 6,
 668: 6,
 669: 6,
 681: 5,
 682: 5,
 683: 5,
 684: 5,
 685: 5,
 708: 5,
 709: 5,
 710: 5,
 711: 5,
 712: 5,
 713: 5,
 714: 5,
 715: 5,
 716: 5,
 717: 5,
 739: 4,
 740: 4,
 741: 4,
 742: 4,
 770: 5,
 771: 5,
 772: 5,
 773: 5,
 774: 5,
 814: 4,
 815: 4,
 816: 4,
 817: 4,
 818: 7,
 819: 7,
 820: 7,
 821: 7,
 822: 7,
 823: 7,
 824: 7,
 841: 5,
 842: 5,
 843: 5,
 844: 5,
 845: 5,
 849: 4,
 850: 4,
 851: 4,
 852: 4}

In [27]:
import pandas as pd

if isinstance(df, (pd.DatetimeIndex, pd.MultiIndex)):
	df = df.to_frame(index=False)

# remove any pre-existing indices for ease of use in the D-Tale code, but this is not required
df = df.reset_index().drop('index', axis=1, errors='ignore')
df.columns = [str(c) for c in df.columns]  # update columns to strings in case they are numbers

corr_data = df.corr(method='pearson')
corr_data.index.name = str('column')
corr_data = corr_data.reset_index()

In [28]:
corr_data

           column    number  orbital_period      mass  distance      year
0          number  1.000000       -0.012570 -0.241429 -0.033638  0.147849
1  orbital_period -0.012570        1.000000  0.173725 -0.034365 -0.032333
2            mass -0.241429        0.173725  1.000000  0.274082 -0.123787
3        distance -0.033638       -0.034365  0.274082  1.000000  0.178922
4            year  0.147849       -0.032333 -0.123787  0.178922  1.000000